services:
  postgres:
    image: postgres:16
    volumes:
      - ./database_data:/var/lib/postgresql/data
      - ./init-data.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"