drop database if exists travel;

create database travel;

\connect travel

-- CREATE SCHEMA flights;

-- SET search_path = flights, pg_catalog;
-- SET search_path = public;

create table airports (
    code text,
    name text,
    city_id bigint
);

create table cities (
    id bigint generated by default as identity,
    name text,
    country text
);

insert into cities(id, name, country)
values (1, 'Санкт-Петербург', 'Россия');

insert into airports
values ('LED', 'Пулково', 1);